language: node_js
node_js:
  - "7"
services:
  - docker
script:
  # first build project locally
  - npm i
  - gulp
  # now build project with a docker image
  - ./create-docker-image.sh
  - ./build.sh

